apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      # Optional: force scheduling to a specific node.
      # Remove or comment this line if you want Kubernetes to schedule the pod automatically.
      nodeName: gke-kub-cluster-main1-default-pool-6d2f5c5a-q69n
      containers:
      - name: inference-container
        image: us-east1-docker.pkg.dev/performance-modeling-analysis/training-image/inference-image1:latest
        command: ["python3", "inference.py"]
        ports:
        - protocol: TCP
          containerPort: 8080
          
        volumeMounts:
        - name: model-volume
          mountPath: /model
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: pvc-model-bucket
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  type: LoadBalancer  # Or use NodePort for testing externally
  selector:
    app: inference
  ports:
  - protocol: TCP
    port: 8080          # External port to access the service
    targetPort: 8080  # Must match the containerPort in the Deployment
